### ISSUE TITLE
Css & install 1.1.3

### ISSUE THREAD

**Issue by seballot** [seballot/ep_embedded_hyperlinks#1]
From @revast:

How would I get 1.1.3? via the plugin manager? I alterd index.js by hand for now

I also have these minor issues (with the css, it seems??):

![image](https://user-images.githubusercontent.com/17404254/70370672-5e227b80-18ca-11ea-8bf5-d35630b76617.png)

The button is a bit lower then the others
Underlying text is to be shown underneath the OK button (propably also because of this offset)

**Comment by seballot** [comment]
re 1.1.3, you can run

`npm update ep_embedded_hyperlinks2`

re the css, the plugin has been changed to fit better with new etherpad default theme, which is 'colibris'. Please change your theme to colibris to order to improve the UI

**Comment by revast** [comment]
Ok thanks. I just happen to have the windows 1.7.5 Version now, and it seems there is no npm included there? I just see node.exe
It this new theme also availablie in 1.7.5?

**Comment by seballot** [comment]
Oh I do not know how it work on windows, sorry...

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by muxator** [comment]
Hi @revast,

> It this new theme also availablie in 1.7.5?

yes it is. You can see the relevant files in `src/static/skins/colibris`, but this is just a detail. You should be able to activate colibris just editing your `settings.json`.

> I just happen to have the windows 1.7.5 Version now, and it seems there is no npm included there? I just see node.exe
That's true, there is no `npm` toplevel, and it's an overlook in the windows package.

/hackish mode on
Actually you _have_ an `npm`, because is an etherpad dependency and it's located in `<zipbase>node_modules/ep_etherpad-lite/node_modules/npm/bin`. It may just a question of fiddling with paths. I am no windows user so I cannot give you much support right now.

**Edit**: upon further consideration, you may just be able to install your plugin via the admin interface. Under the hood, it actually uses the npm I indicated before to perform the installation.

**Comment by revast** [comment]
ok Thanks! I am gonna try.

**Comment by revast** [comment]
hello, the embedded hyperlinks plugin in the plugin interface still is version 1.1.1 
I tried to uninstall and reinstall, but that does not work:

[2020-01-02 10:29:57.139] [INFO] console - + ep_embedded_hyperlinks2@1.1.3
added 1 package from 1 contributor in 1.55s
[2020-01-02 10:29:58.520] [ERROR] console - Unable to parse plugin definition file C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_embedded_hyperlinks2\ep.json: SyntaxError: Unexpected token } in JSON at position 767
[2020-01-02 10:29:58.529] [ERROR] console - Failed to load 'C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_copy_paste_images\static\js\index' for 'ep_copy_paste_images/ep_copy_paste_images/hooks/collectContentPre': ReferenceError: window is not defined
[2020-01-02 10:29:58.533] [ERROR] console - Failed to load 'C:\Users\Florian\Downloads\etherpad-lite-win-1.7.5-6a3e4c69b8\node_modules\ep_copy_paste_images\static\js\index' for 'ep_copy_paste_images/ep_copy_paste_images/hooks/collectContentPost': ReferenceError: window is not defined

in fact, the plugin does not work at all now, and it is not installed from plugin manager... hmmm

 ep_embedded_hyperlinks2@1.1.3 so it fetches 1.1.3, but in the interface, it says 1.1.1 .. strange...

also, the plugin page stats its not installed, but in fact, the folder is generated in the filesystem...

I have also found that the new theme is not yet working good with the "resizable bars" plugin, the bars of the toc and chat bar are displayed, but one cannot resize them... I should report this @etherpad github issues I guess?

**Comment by seballot** [comment]
Hi ! fixed now, on 1.1.5

Strange that we did not get this error in the past... maybe something changed on etherpad core code

re resizable bars, yes you can create an issue on main etherpad code : https://github.com/ether/etherpad-lite
And assign it to me, or mention me at least, I will see what I can do

**Comment by seballot** [comment]
Actually I had a look with resizable bars plugin, I fixed it and made a pull request : https://github.com/seballot/ep_embedded_hyperlinks2/issues/1
