### ISSUE TITLE
Feature Request: Simplify linking to another pad

### ISSUE THREAD

**Issue by mmccarn** [seballot/ep_embedded_hyperlinks#17]
I used to make heavy use of ep_linkify, which I can not find online to add back to my system.

If the code for the default protocol in ep_embedded_hyperlinks2 is modified slightly, users could create links to another pad simply by typing the filename portion of the pad's URL (that is, the pad name with illegal characters converted to underscores).

Proposed change:

```
56  - url = "http://" + url;
56  + url = window.location.origin + "/p/" + url;
```

Now if I want to link to another pad on my server, I simply paste the pad name into the 'URL' field (and replace spaces etc with underscores)

**Comment by seballot** [comment]
Hi ! yes it will work for your specific case, but this plugin is to add any link on a pad, so if I put `duckduckgo.com` I don't expect to create a link like `http://pad.my-server.fr/p/duckduckgo.com` ...
