### ISSUE TITLE
[Bug] Copy embedded hyperlink doesn't work

### ISSUE THREAD

**Issue by Oremountainflorian** [seballot/ep_embedded_hyperlinks#3]
**Description**

When I create a single hyperlink in a line and copy it to the next line, it's gone. When I wrap some text arround, it still works, but the link is corrupted. Furthermore, it's not possible to copy the link by selecting the text somehow. 

Would be really cool if you could fix that! :) Thank you very much for your commitment!

**Comment by manu-p** [comment]
Hi, 
Same observation on our installation. This module becomes unusable, especially if we add that the hyperlinks are lost when exporting ODF or PDF ...

**Comment by Oremountainflorian** [comment]
More comprehensive update in https://github.com/seballot/ep_embedded_hyperlinks2/issues/7
